import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import { Providers } from '@/providers/Providers';

// const oswald = Oswald({
//   variable: '--font-oswald',
//   subsets: ['latin'],
//   weight: ['200', '300', '400', '500', '600', '700'],
// });

// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
// });

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body className={`${quicksand.variable} antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
